extends:
  - react-app
  - ../.eslintrc.yml
parserOptions:
  project: ./tsconfig.json
overrides:
  - files:
      - vite.config.ts
    parserOptions:
      project: ./tsconfig.node.json
rules:
  '@typescript-eslint/no-restricted-imports':
    - error
    - patterns:
        - group:
            - '@assistant/backend/**'
            - '!@assistant/backend/src/router'
            - '!@assistant/backend/**/'
            - '!@assistant/backend/**/input'
            - '!@assistant/backend/src/utils/can'
          allowTypeImports: true
          message: 'Only types and input schemas are allowed to be imported from backend workspace'
